config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :products


  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PragProg Books Online Store
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{class: "#{controller.controller_name}"}
    #banner
      %span.title= @page_title
    #columns
      #side
        #cart{style: @cart.try(:line_items).try(:empty?) ? 'display: none;' : ''}
          = render @cart if @cart
        %ul
          %li= link_to t('.home'), store_index_path
          %li= link_to t('.questions'), '/faq'
          %li= link_to t('.news'), '/news'
          %li= link_to t('.contact'), '/contact'
        - if session[:user_id]
          %ul
            %li= link_to 'Orders', orders_path
            %li= link_to 'Products', products_path
            %li= link_to 'Users', users_path

          = button_to 'Log out', logout_path, method: :delete
      /yield = current displaying, like ng-views in angular
      #main
        = yield